### PR TITLE
oli_lab updates

### PR DESCRIPTION
**Pull request by Oli-Lab**
I think I'm lost !

### CODE REVIEW

**Comment by ab5tract** [comment]
:)

**Comment by ab5tract** [comment]
You can imagine it like a more pedantic form dropbox: whatever you alter or add to the repository will only be synced 'upstream' when you explicitly 'commit' the changes.

Furthermore, committing new files is a separate 'staging' operation than committing changes to existing files.

Luckily we are on the nicest git site around! Are you currently using the GUI version of the github tool?

**Comment by Oli-Lab** [comment]
no I was online

2015-05-02 17:17 GMT+02:00 ab5tract notifications@github.com:

> You can imagine it like a more pedantic form dropbox: whatever you alter
> or add to the repository will only be synced 'upstream' when you explicitly
> add it.
> 
> Are you currently using the GUI version of the github tool?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ab5tract/hollyhock-grove/pull/1#issuecomment-98370628
> .

## 

_///////////////////////////////////////////////////////////////////Oli_Lab_
Laboratoire de développement pour les Arts

olilab101@gmail.com

http://oli-lab.org http://oli.lab.free.fr

_///////////////////////////////////////////////////////////////////_

**Comment by Oli-Lab** [comment]
now I installed the software on my WIN8 PC...still don't get what to do next : 
a fork on your grove, then a pull request.
I'll do that when next modules are ready
but for now I'm making music and a visual-for-sound game on Processing based on a giant planet thrower gun...

**Comment by ab5tract** [comment]
WOW! That game sounds awesome :D

**Pull request merged**
