### PR TITLE
update

### PR DESCRIPTION
**Pull request by Oli-Lab**
can't get the logic behind this Git !

### CODE REVIEW

**Comment by ab5tract** [comment]
Thanks Oli-Lab!

**Comment by Oli-Lab** [comment]
I don't think its the whole lot, I had a terrible time last nigth with GitHub !!!

**Comment by Oli-Lab** [comment]
what I don't understand is how to make a new folder.

**Comment by ab5tract** [comment]
You should be able to create one in the git repo itself (through Windows
Explorer).

It won't be added to git until you commit a file within that new directory
(using git add). Empty folders can't be added AFAIK.

**Comment by Oli-Lab** [comment]
do you mean into your repo or my branch ?
I'm totally lost, I can't even figure out I did it right in may !

**Comment by ab5tract** [comment]
into your clone. i think you have a copy on your hard drive, right? then
you commit it, push it, and then submit a PR as you did before.

are you using the GUI client?

**Comment by Oli-Lab** [comment]
yes, the gui client, I did all that but seem to refuse to commit, I'll try
later on

thanx

2016-02-23 15:06 GMT+01:00 ab5tract notifications@github.com:

> into your clone. i think you have a copy on your hard drive, right? then
> you commit it, push it, and then submit a PR as you did before.
> 
> are you using the GUI client?
> 
> On Tue, Feb 23, 2016 at 2:18 PM olivar notifications@github.com wrote:
> 
> > do you mean into your repo or my branch ?
> > I'm totally lost, I can't even figure out I did it right in may !
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ab5tract/hollyhock-grove/pull/5#issuecomment-187694229>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ab5tract/hollyhock-grove/pull/5#issuecomment-187712303
> .

## 

_///////////////////////////////////////////////////////////////////Oli_Lab_
Laboratoire de développement pour les Arts

olilab101@gmail.com

http://oli-lab.org http://oli.lab.free.fr

_///////////////////////////////////////////////////////////////////_

**Comment by Oli-Lab** [comment]
I need you email for "we transfer"...the git is way too criptic for me !
thanx

olilab101[^]gmail.com

2016-02-23 16:11 GMT+01:00 Olivar Premier olilab101@gmail.com:

> yes, the gui client, I did all that but seem to refuse to commit, I'll try
> later on
> 
> thanx
> 
> 2016-02-23 15:06 GMT+01:00 ab5tract notifications@github.com:
> 
> > into your clone. i think you have a copy on your hard drive, right? then
> > you commit it, push it, and then submit a PR as you did before.
> > 
> > are you using the GUI client?
> > 
> > On Tue, Feb 23, 2016 at 2:18 PM olivar notifications@github.com wrote:
> > 
> > > do you mean into your repo or my branch ?
> > > I'm totally lost, I can't even figure out I did it right in may !
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/ab5tract/hollyhock-grove/pull/5#issuecomment-187694229
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ab5tract/hollyhock-grove/pull/5#issuecomment-187712303
> > .
> 
> ## 
> 
> _///////////////////////////////////////////////////////////////////Oli_Lab_
> Laboratoire de développement pour les Arts
> 
> olilab101@gmail.com
> 
> http://oli-lab.org http://oli.lab.free.fr
> 
> _///////////////////////////////////////////////////////////////////_

## 

_///////////////////////////////////////////////////////////////////Oli_Lab_
Laboratoire de développement pour les Arts

olilab101@gmail.com

http://oli-lab.org http://oli.lab.free.fr

_///////////////////////////////////////////////////////////////////_

**Pull request merged**
